### ISSUE TITLE
`sysappdb process` does not handle hexidecimal priorities in AndroidManifest.xml

### ISSUE THREAD

**Issue by jakev** [jakev/dtfmods-core#10]
Traceback (most recent call last):
  File "/repos/dtf/modules/sysappdb", line 2042, in <module>
    exit(main(argv))
  File "/repos/dtf/modules/sysappdb", line 2031, in main
    return cmdProcess(argv)
  File "/repos/dtf/modules/sysappdb", line 1888, in cmdProcess
    parseServices(appdb, project_id, manifest_path)
  File "/repos/dtf/modules/sysappdb", line 923, in parseServices
    appdb.addServiceIntentFilter(intent_filter, _id)
  File "/repos/dtf/lib/AppDb/AppDb.py", line 929, in addServiceIntentFilter
    priority = int(intent_filter.getPriority())
ValueError: invalid literal for int() with base 10: '0x7fffffff'

**Comment by jakev** [comment]
fixed: https://github.com/jakev/dtfmods-core/commit/85d8098a2b5759be7c5da4825b9f361edc1b799d
