### ISSUE TITLE
`sysappdb process` doesn't confirm the manifest exists before attempting to open

### ISSUE THREAD

**Issue by jakev** [jakev/dtfmods-core#45]
Traceback (most recent call last):
  File "/usr/local/bin/dtf", line 185, in <module>
    sys.exit(main())
  File "/usr/local/bin/dtf", line 175, in main
    rtn = pkg.launch_module(command_name, sys.argv)
  File "/usr/local/lib/python2.7/dist-packages/dtf/packages.py", line 188, in launch_module
    return __launch_python_module(module_path, cmd, args)
  File "/usr/local/lib/python2.7/dist-packages/dtf/packages.py", line 97, in __launch_python_module
    return mod_inst.run(args)
  File "/usr/local/lib/python2.7/dist-packages/dtf/module.py", line 62, in run
    result = getattr(self, 'execute')(args)
  File "/home/analyst/.dtf/modules//sysappdb", line 2657, in execute
    return self.cmd_process(args)
  File "/home/analyst/.dtf/modules//sysappdb", line 2499, in cmd_process
    self.do_final_pass(appdb)
  File "/home/analyst/.dtf/modules//sysappdb", line 1429, in do_final_pass
    self.parse_debuggable(appdb, project_id, manifest_path)
  File "/home/analyst/.dtf/modules//sysappdb", line 1163, in parse_debuggable
    manifest_f = open(manifest_path)
IOError: [Errno 2] No such file or directory: u'decoded-oem/com.test/AndroidManifest.xml

**Comment by jakev** [comment]
Fixed: https://github.com/jakev/dtfmods-core/commit/28ef4a928f2d5ea336937e857edbd4fd819a6e74
